version: '3.7'
services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs:ro
    networks:
      - jira-proxy

  jira:
    container_name: jira
    image: atlassian/jira-software:9.12.9
    restart: unless-stopped
    volumes:
      - var:/var/atlassian/application-data/jira
      - opt:/opt/atlassian/jira
      - ./activate:/opt/atlassian/atlassian-agent/
    environment:
      - 'JVM_MINIMUM_MEMORY=2048m'
      - 'JVM_MAXIMUM_MEMORY=4096m'
      - 'ATL_PROXY_NAME=jira.domain.local'
      - 'ATL_PROXY_PORT=443'
      - 'ATL_TOMCAT_SCHEME=https'
      - 'TZ=Europe/Moscow'
    networks:
      - jira-proxy

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: jiradb
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jiradb
      PGDATA: /data/postgres
    volumes:
       - ./postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - jira-proxy

networks:
  jira-proxy:

volumes:
  var:
    external: false
  opt:
    external: false
